/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DtoUpdateProductDto struct {
	Description string `json:"description"`

	Name string `json:"name"`

	Price float32 `json:"price"`

	ProductId string `json:"productId"`
}

// AssertDtoUpdateProductDtoRequired checks if the required fields are not zero-ed
func AssertDtoUpdateProductDtoRequired(obj DtoUpdateProductDto) error {
	elements := map[string]interface{}{
		"description": obj.Description,
		"name":        obj.Name,
		"price":       obj.Price,
		"productId":   obj.ProductId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDtoUpdateProductDtoConstraints checks if the values respects the defined constraints
func AssertDtoUpdateProductDtoConstraints(obj DtoUpdateProductDto) error {
	return nil
}
