/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DtoProductsListResponse struct {
	HasMore bool `json:"hasMore,omitempty"`

	Page int32 `json:"page,omitempty"`

	Products []DtoProductResponse `json:"products,omitempty"`

	Size int32 `json:"size,omitempty"`

	TotalCount int32 `json:"totalCount,omitempty"`

	TotalPages int32 `json:"totalPages,omitempty"`
}

// AssertDtoProductsListResponseRequired checks if the required fields are not zero-ed
func AssertDtoProductsListResponseRequired(obj DtoProductsListResponse) error {
	for _, el := range obj.Products {
		if err := AssertDtoProductResponseRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertDtoProductsListResponseConstraints checks if the values respects the defined constraints
func AssertDtoProductsListResponseConstraints(obj DtoProductsListResponse) error {
	return nil
}
