/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DtoCreateProductResponseDto struct {
	ProductId string `json:"productId"`
}

// AssertDtoCreateProductResponseDtoRequired checks if the required fields are not zero-ed
func AssertDtoCreateProductResponseDtoRequired(obj DtoCreateProductResponseDto) error {
	elements := map[string]interface{}{
		"productId": obj.ProductId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertDtoCreateProductResponseDtoConstraints checks if the values respects the defined constraints
func AssertDtoCreateProductResponseDtoConstraints(obj DtoCreateProductResponseDto) error {
	return nil
}
