/*
 * Title
 *
 * Title
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DtoProductResponse struct {
	CreatedAt string `json:"createdAt,omitempty"`

	Description string `json:"description,omitempty"`

	Name string `json:"name,omitempty"`

	Price float32 `json:"price,omitempty"`

	ProductId string `json:"productId,omitempty"`

	UpdatedAt string `json:"updatedAt,omitempty"`
}

// AssertDtoProductResponseRequired checks if the required fields are not zero-ed
func AssertDtoProductResponseRequired(obj DtoProductResponse) error {
	return nil
}

// AssertDtoProductResponseConstraints checks if the values respects the defined constraints
func AssertDtoProductResponseConstraints(obj DtoProductResponse) error {
	return nil
}
